#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 10, 2022 10:24:58 PM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter import filedialog
from tkinter.constants import *

from PIL import ImageTk, Image

import conduire_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("872x568+219+46")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#bebebe")

        self.top = top

        self.Label2_1 = tk.Label(self.top)
        self.Label2_1.place(relx=0.05, rely=0.268, height=266, width=368)
        self.Label2_1.configure(activebackground="#0d0003")
        self.Label2_1.configure(activeforeground="white")
        self.Label2_1.configure(activeforeground="#000000")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#ffffff")
        self.Label2_1.configure(compound='center')
        self.Label2_1.configure(disabledforeground="#000000")
        self.Label2_1.configure(font="-family {Segoe UI} -size 20")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="#030004")
        self.Label2_1.configure(highlightthickness="3")
        self.Label2_1.configure(text='''RECTO''')

        self.Label2_1_1 = tk.Label(self.top)
        self.Label2_1_1.place(relx=0.528, rely=0.264, height=266, width=369)
        self.Label2_1_1.configure(activebackground="#0d0003")
        self.Label2_1_1.configure(activeforeground="white")
        self.Label2_1_1.configure(activeforeground="#000000")
        self.Label2_1_1.configure(background="#ffffff")
        self.Label2_1_1.configure(compound='center')
        self.Label2_1_1.configure(disabledforeground="#000000")
        self.Label2_1_1.configure(font="-family {Segoe UI} -size 20")
        self.Label2_1_1.configure(foreground="#000000")
        self.Label2_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1_1.configure(highlightcolor="black")
        self.Label2_1_1.configure(highlightthickness="3")
        self.Label2_1_1.configure(text='''VERSO''')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.367, rely=0.81, height=24, width=77)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Button''')

        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.523, rely=0.822, height=24, width=67)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Button''')

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.055, rely=0.157, height=24, width=57)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(compound='left')
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Button''')
        self.Button3.configure(command=upload_file1(self.Label2_1))

        self.Button3_1 = tk.Button(self.top)
        self.Button3_1.place(relx=0.522, rely=0.157, height=24, width=57)
        self.Button3_1.configure(activebackground="#ececec")
        self.Button3_1.configure(activeforeground="#000000")
        self.Button3_1.configure(background="#d9d9d9")
        self.Button3_1.configure(compound='left')
        self.Button3_1.configure(disabledforeground="#a3a3a3")
        self.Button3_1.configure(foreground="#000000")
        self.Button3_1.configure(highlightbackground="#d9d9d9")
        self.Button3_1.configure(highlightcolor="black")
        self.Button3_1.configure(pady="0")
        self.Button3_1.configure(text='''Button''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.167, rely=0.157, height=26, width=267)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Label''')

        self.Label1_1 = tk.Label(self.top)
        self.Label1_1.place(relx=0.642, rely=0.151, height=27, width=268)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(anchor='w')
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(compound='left')
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Label''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.163, rely=0.021, height=40, width=573)
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Imprint MT Shadow} -size 24")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''PERMIS DE CONDUIRE''')

def upload_file(label, label1, label2):
        image_Path = filedialog.askopenfilename(initialdir='C:\\', filetypes=[("png files", '.png')])
        image = tk.Image.open(image_Path)
        image.thumbnail((350, 450))
        image = ImageTk.PhotoImage(image)
        label1.configure(image=image)
        label.image = image
        label2.configure(text=image_Path)

def upload_file1(label2_1):
        image_Path = filedialog.askopenfilename(initialdir='C:\\', filetypes=[("png files", '.png')])
        image = Image.open(image_Path)
        image.thumbnail((350, 450))
        image = ImageTk.PhotoImage(image)
        label2_1.configure(image=image)
        label2_1.image = image


def start_up():
    conduire_support.main()


if __name__ == '__main__':
    conduire_support.main()




